---
title: "drill nov 2021-mar 2022"
author: "Maria Stahl"
date: "4/20/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list = ls())
```

## Load necessary packages
```{r}
library(amt)
library(dplyr)
library(ggplot2)
# library(glmnetUtils)
# library(hms)
library(lubridate)
# library(raster)
library(rgdal)
# library(rlist)
library(sf)
# library(stats)
library(tidyr)
library(tmap)
```

## Load in Drill Pasture shapefile
```{r}
drill_pasture = readOGR("Drill_Pasture/Drill_Pasture.shp")
drill_pasture_sf = st_read("Drill_Pasture/Drill_Pasture.shp")
```

## Load in collar data
```{r}
# retrieve file names
path = '../Data/Collar Data March 2022/gps'
files = list.files(path = path, all.files = T, full.names = T)[3:14] %>%
  as.list()

# retrieve collar serial numbers
collars = list.files(path = path, all.files = T, full.names = F)[3:14] %>%
  substr(start = 10, stop = 14)

# read in files
cattle.dat.nov2021 = lapply(X = files, FUN = read.csv, skip = 3)
cattle.dat.nov2021 = lapply(1:length(cattle.dat.nov2021), 
           function(id) cbind(cattle.dat.nov2021[[id]], id))
cattle.frame.nov2021 = as.data.frame(do.call(rbind, cattle.dat.nov2021))
CollarID = collars[cattle.frame.nov2021$id]
cattle.frame.nov2021 = cbind(CollarID, cattle.frame.nov2021)[1:10]

# check how many individuals are in dataset
length(collars)

# data in UTM
cattle.gps.new = st_as_sf(cattle.frame.nov2021, 
                          coords = c('Longitude', 'Latitude'))
st_crs(cattle.gps.new) = CRS("+proj=longlat +ellps=WGS84")
cattle.gps.new = st_transform(cattle.gps.new, crs = st_crs(drill_pasture))

ctmm::projection(cattle.gps.new) == ctmm::projection(drill_pasture)

cattle.utm.new = as_Spatial(cattle.gps.new)

rm(cattle.gps.new)

### Check last day of data for all collars
cattle.utm.new@data$date_time = as.POSIXct(cattle.utm.new$GMT.Time, tz = 'GMT',
                                 format = '%m/%d/%Y %H:%M:%S %p') %>%
  with_tz(tz = 'US/Mountain')

#########
last_day_collars = tapply(X = cattle.utm.new$Date, 
                          INDEX = cattle.utm.new$CollarID,
                          FUN = max)
last_day_collars
```

## add collar metadata
```{r}
metadata = read.csv('../Data/collars.peds_Mar22.csv')
names(metadata)[3] = 'CollarSerialNumber'

drill.points.sf = st_as_sf(cattle.utm.drill) %>%
  merge(metadata, by = 'CollarSerialNumber')

drill.points.sf$CollarSerialNumber = as.factor(drill.points.sf$CollarSerialNumber)
```

# clean up dataframe
```{r}
drill.points.sf$date = as.Date(drill.points.sf$Julianday, origin = '2021-12-31')
```

# add water and salt
```{r}
features = read_sf('Drill 2020 water and salt.kml')
features$Name = c('trough1', 'trough2', 'trough3', 'trough4', 'trough5',
                  'salt_lick1', 'salt1', 'salt2', 'salt3', 'salt_lick4', 
                  'creek_trough')
features$Description = c('water', 'water', 'water', 'water', 'water', 'salt',
                         'salt', 'salt', 'salt', 'salt', 'outside')
features$geometry = st_transform(features$geometry, 
                                 crs = st_crs(drill_pasture_sf))
```

## plot points
```{r}
# ANGUS
ggplot() +
  geom_sf(data = subset(drill.points.sf, breed == 'Angus' & Julianday > 75), 
                        aes(color = CollarSerialNumber), alpha = 0.5) +
  geom_sf(data = drill_pasture_sf, aes(), fill = NA) +
  geom_sf(data = features[1:10,], aes(shape = Description), alpha = 0.8) +
  facet_wrap(~date) +
  scale_x_continuous(breaks = seq(621000, 624000, length.out = 2)) +
  scale_y_continuous(breaks = seq(4221000, 4225000, length.out = 3)) +
  coord_sf(datum = sf::st_crs(drill_pasture)) +
  theme(text = element_text(color = "black", size = 20),
        legend.key.size = unit(1.5, 'cm')) +
  guides(color = 'none')

# CRIOLLO
ggplot() +
  geom_sf(data = subset(drill.points.sf, breed == 'Criollo' & Julianday > 75), 
                        aes(color = CollarSerialNumber), alpha = 0.5) +
  geom_sf(data = drill_pasture_sf, aes(), fill = NA) +
  geom_sf(data = features[1:10,], aes(shape = Description), alpha = 0.8) +
  facet_wrap(~date) +
  scale_x_continuous(breaks = seq(621000, 624000, length.out = 2)) +
  scale_y_continuous(breaks = seq(4221000, 4225000, length.out = 3)) +
  coord_sf(datum = sf::st_crs(drill_pasture)) +
  theme(text = element_text(color = "black", size = 20),
        legend.key.size = unit(1.5, 'cm')) +
  guides(color = 'none')
```

